<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Kavenegar" Version="1.2.5" />
    <PackageReference Include="LazZiya.ImageResize" Version="4.1.4" />
    <PackageReference Include="Microsoft.AspNetCore.Http" Version="2.3.10" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="SixLabors.ImageSharp" Version="2.1.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EShop.Data\EShop.Data.csproj" />
  </ItemGroup>

</Project>